### ISSUE TITLE
Using orb fails on circleci with "Invalid reference format"

### ISSUE THREAD

**Issue by einSelbst** [fossas/fossa-cli-orb#5]
### Orb version

My ``circleci/config.yml`` looks like this:

```
version: 2.1
orbs:
  fossa-cli: fossa/cli@0.0.3
workflows:
  fossa-integration:
    jobs:
      - fossa-cli/analyze
```

### What happened

It fails on circleci with the following error:

```
Build-agent version 1.0.15283-35354d0e (2019-09-09T12:09:35+0000)
Docker Engine Version: 18.09.6
Kernel Version: Linux e605db5d2288 4.15.0-1043-aws #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64 Linux
Starting container cimg/base@2019.08-node
  image cache not found on this host, downloading cimg/base@2019.08-node

invalid reference format
```

### Expected behavior

When I use the circleci integration without the orb it works. BTW the docs don't mention that an orb even exists. I just found this via your blog post.
